### PR TITLE
Exclude tests directory when looking for packages

### PR DESCRIPTION
**Pull request by likewhoa**

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Hey @likewhoa 👋 Could you explain what this is for? As far as I can see the tests are already excluded from the package in MANIFEST.in: https://github.com/springload/draftjs_exporter/blob/master/MANIFEST.in#L5

**Comment by likewhoa** [comment]
> Hey @likewhoa  Could you explain what this is for? As far as I can see the tests are already excluded from the package in MANIFEST.in: https://github.com/springload/draftjs_exporter/blob/master/MANIFEST.in#L5

Sure, take a look at the build log here http://dpaste.com/301FAEP#line-211 I basically packaged it for Gentoo Linux.

**Comment by thibaudcolas** [comment]
Got it! Do you have further info so I know what to test? I don’t have a Gentoo build available. 

Does this mean the similar exclude in Manifest.in is useless?

**Comment by likewhoa** [comment]
> Got it! Do you have further info so I know what to test? I don’t have a Gentoo build available.
> 
> Does this mean the similar exclude in Manifest.in is useless?

Yes just doing

`
git clone https://github.com/springload/draftjs_exporter.git
cd draftjs_exporter
mkdir install-here
python3.6 setup.py build
python3.6 setup.py install --root=install-here
`
It installs the 'tests' directory in 'install-here/usr/lib64/python3.6/site-packages/tests' which is totally wrong since the actual package is installed in 'install-here/usr/lib64/python3.6/site-packages/draftjs_exporter/'

So it looks like the MANIFEST.in is correct but for some reason after 'setup.py install' it's installing the tests directory even though 'draftjs_exporter.egg-info/SOURCES.txt' doesn't show it. My changes fixes this.

**Pull request merged**
